In [ ]:
#EXAMPLE FOR WEB SCAPPING:

#importing the BeautifulSoup Library

import bs4
import requests

#Creating the requests

res = requests.get("https://en.wikipedia.org/wiki/Machine_learning")
print("The object type:",type(res))

# Convert the request object to the Beautiful Soup Object
soup = bs4.BeautifulSoup(res.text,'html5lib')
print("The object type:",type(soup))

The object type: <class 'requests.models.Response'>
The object type: <class 'bs4.BeautifulSoup'>


In [ ]:
#In the following lines of code, we are extracting all headings of a webpage by class name.
#Here front-end knowledge plays an essential role in inspecting the webpage.
soup.select('.mw-headline')
for i in soup.select('.mw-headline'):
   print(i.text,end = ',')

History and relationships to other fields,Artificial intelligence,Data mining,Generalization,Statistics,Statistical Physics, Theory,Approaches,Supervised learning,Unsupervised learning,Semi-supervised learning,Reinforcement learning,Dimensionality reduction,Other types,Self-learning,Feature learning,Sparse dictionary learning,Anomaly detection,Robot learning,Association rules,Models,Artificial neural networks,Decision trees,Support-vector machines,Regression analysis,Bayesian networks,Gaussian processes,Genetic algorithms,Belief functions,Training models,Federated learning,Applications,Limitations,Bias,Explainability,Overfitting,Other limitations and vulnerabilities,Model assessments,Ethics,Hardware,Neuromorphic/Physical Neural Networks,Embedded Machine Learning,Software,Free and open-source software,Proprietary software with free and open-source editions,Proprietary software,Journals,Conferences,See also,References,Sources,Further reading,External links,

In [ ]:
#Example for Webpage of Wikipedia Learning

# importing the libraries
from bs4 import BeautifulSoup
import requests

url="https://www.javatpoint.com/"

# Make a GET request to fetch the raw HTML content
html_content = requests.get(url).text

# Parse the html content
soup = BeautifulSoup(html_content, "html5lib")
print(soup.prettify()) # print the parsed data of html

In [ ]:
#Print the title of the web page.
print(soup.title)

<title>Tutorials List - Javatpoint</title>


In [ ]:
#In the above output, the HTML tag is included with the title. If you want text without tag, you can use the following code:
print(soup.title.text)

Tutorials List - Javatpoint


In [ ]:
#We can get the entire link on the page along with its attributes, such as href, title, and its inner Text. Consider the following code:
for link in soup.find_all("a"):
   print("Inner Text is: {}".format(link.text))
   print("Title is: {}".format(link.get("title")))
   print("href is: {}".format(link.get("href")))

In [ ]:
#A Step-by-step Guide on Python Web Scraping a Wikipedia Page

#Step 1: Fetch the web page and convert the HTML page into text with the help of the Python request library
#import the python request library to query a website
import requests
#specify the url we want to scrape from
Link = "https://en.wikipedia.org/wiki/Forbes_list_of_Indian_billionaires"
#convert the web page to text
Link_text = requests.get(Link).text
print(Link_text)

In [ ]:
#Step 2: In order to fetch useful information, convert Link_text (which is of string data type) into a BeautifulSoup object. Import BeautifulSoup library from bs4
#import BautifulSoup library to pull data out of HTML and XML files
from bs4 import BeautifulSoup
#to convert Link_text into a BeautifulSoup Object
soup = BeautifulSoup(Link_text, 'lxml')
print(soup)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-0 vector-feature-client-preferences-disabled vector-feature-client-prefs-pinned-disabled vector-toc-not-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Forbes list of Indian billionaires - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vec

In [ ]:
#Step 3: With the help of the prettify() function, make the indentation proper
#make the indentation proper
print(soup.prettify())

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-0 vector-feature-client-preferences-disabled vector-feature-client-prefs-pinned-disabled vector-toc-not-available" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Forbes list of Indian billionaires - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-widt

In [ ]:
#Step 4: To fetch the web page title, use soup.title
#To take a look at the title of the web page
print(soup.title)

<title>Forbes list of Indian billionaires - Wikipedia</title>


In [ ]:
#Step 5: We want only the string part of the title, not the tags
#Only the string not the tags
print(soup.title.string)

Forbes list of Indian billionaires - Wikipedia


In [ ]:
#Step 6: We can also explore <a></a> tags in the soup object
#First <a></a> tag
soup.a

<a class="mw-jump-link" href="#bodyContent">Jump to content</a>

In [ ]:
#Step 7: Explore all <a></a> tags
#all the <a> </a> tags
soup.find_all('a')

[<a class="mw-jump-link" href="#bodyContent">Jump to content</a>,
 <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a>,
 <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a>,
 <a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a>,
 <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a>,
 <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a>,
 <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a>,
 <a href="https://donate.wikimedia.org/wiki/Special:FundraiserRedirector?utm_source=donate&amp;utm_medium=sidebar&amp;utm_campaign=C13_en.wikipedia.org&amp;uselang=en" title="Support us by donating to the Wikimedia Foundation"><span>Donate</span></a>,
 <a href=

In [ ]:
#Step 8: Again, just the way we fetched title tags, we will fetch all table tags
#Fetch all the table tags
all_table = soup.find_all('table')
print(all_table)

[<table class="plainlinks fmbox fmbox-system" id="noarticletext" role="presentation"><tbody><tr><td class="mbox-text" style="padding: 0.6em 0.9em;"><style data-mw-deduplicate="TemplateStyles:r1080588920">.mw-parser-output .no-article-text-sister-projects{border:1px solid #a2a9b1;background-color:#f8f9fa;line-height:1.5em;font-size:90%;padding:0.5em}.mw-parser-output .no-article-text-sister-projects li{display:flex;align-items:center}.mw-parser-output .no-article-text-sister-projects li>div:first-child{text-align:center;width:30px;height:30px;margin-right:0.3em;flex:0 0 30px}@media all and (min-width:40em){.mw-parser-output .no-article-text-sister-projects{margin:0.5em 0 0.5em 1em;clear:right;width:20em;float:right}.mw-parser-output .no-article-text-sister-projects .plainlist{margin-left:2em}.mw-parser-output .no-article-text-sister-projects li{height:2.5em}}</style><div class="no-article-text-sister-projects" id="sisterproject">Look for <b>Forbes list of Indian billionaires</b> on one 

In [ ]:
#Step 9: Since our aim is to get the List of Billionaires from the wiki-page, we need to find out the table class name. Go to the webpage. Inspect the table by placing cursor over the table and inspect the element using ‘Shift+Q’.
#Open browser and search "Forbes India's richest Indian" and "inspect" element find the table table class name is ‘wikitable sortable’.

In [ ]:
#Step 10: Now, fetch all table tags with the class name ‘wikitable sortable’
#fetch all the table tags with class name="wikitable sortable"
our_table = soup.find('table', class_= 'wikitable sortable')
print(our_table)

None


In [ ]:
#1.Submitting Form

#In the below example we use the sign up form of a website by supplying the userid and password value. After the submission of the values we print the response.
import requests

ID_USERNAME = 'signup-user-name'
ID_PASSWORD = 'signup-user-password'
USERNAME = 'username'
PASSWORD = 'yourpassword'
SIGNUP_URL = 'http://codepad.org/login'
def submit_form():
    """Submit a form"""
    payload = {ID_USERNAME : USERNAME, ID_PASSWORD : PASSWORD,}

    resp = requests.get(SIGNUP_URL)
    print("Response to GET request: %s" %resp.content)

    resp = requests.post(SIGNUP_URL, payload)
    print("Headers from a POST request response: %s" %resp.headers)
#print "HTML Response: %s" %resp.read()

if __name__ == '__main__':
    submit_form()

Response to GET request: b'<!DOCTYPE html>\n<html>\n\n<head>\n\n    <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n    <meta HTTP-EQUIV="Pragma" CONTENT="no-cache">\n    <meta HTTP-EQUIV="Expires" CONTENT="-1">\n\n    <title>Login - codepad</title>\n\n    \n\n    <link href="/main.css" media="screen" rel="stylesheet" type="text/css" />\n    <style type="text/css">\n    \n\n    </style>\n    <script src=\'https://www.google.com/recaptcha/api.js\'></script>\n    <script>\n       function onRecaptcha(token) {\n         document.getElementById("editor-form").submit();\n       }\n    </script>\n</head>\n\n\n    <body >\n\n\n        <table width="100%" cellpadding="0" cellspacing="0" style="border-bottom: 1px solid #ccc; margin: 0; width: 100%; padding: 8px 8px 4px 8px;"><tr>\n        <td style="text-align: left">\n        <span class="logo"><a href="/">codepad</a></span>\n        <nobr>\n          &nbsp;&nbsp;&nbsp;<span class="menu">[ <a href="/">create a new paste</a

In [ ]:
#2.Fetching web pages

#2.1 Using GET request:

# importing the requests library
import requests

# The API endpoint
url = "https://jsonplaceholder.typicode.com/posts/1"

# A GET request to the API
response = requests.get(url)

# Print the response
response_json = response.json()    #JSON:Java Script Object Notation
print(response_json)

"""
{'userId': 1, 'id': 1, 'title': 'VCET MCA', 'body': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbb\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}
"""


{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}


"\n{'userId': 1, 'id': 1, 'title': 'VCET MCA', 'body': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbb\x07aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}\n"

In [ ]:
# Print status code from original response (not JSON)
print(response.status_code)

"""
200
"""

200


'\n200\n'

In [ ]:
#2.2 Using POST request:
#GET requests allow you to retrieve data; POST requests allow you to create new data.
# Define new data to create
new_data = {
    "userID": 1,
    "id": 1,
    "title": "Making a POST request",
    "body": "This is the data we created."
}

# The API endpoint to communicate with
url_post = "https://jsonplaceholder.typicode.com/posts"

# A POST request to tthe API
post_response = requests.post(url_post, json=new_data)

# Print the response
post_response_json = post_response.json()
print(post_response_json)

"""
{'userID': 1, 'id': 101, 'title': 'Making a POST request', 'body': 'This is the data we created.'}
"""

{'userID': 1, 'id': 101, 'title': 'Making a POST request', 'body': 'This is the data we created.'}


"\n{'userID': 1, 'id': 101, 'title': 'Making a POST request', 'body': 'This is the data we created.'}\n"

In [ ]:
#2.3 Using BeautifulSoap

#Method 1: using bs4 and urllib.
       #bs4: Beautiful Soup(bs4) is a Python library for pulling data out of HTML and XML files
       #urllib: urllib is a package that collects several modules for working with URLs.

# importing modules
import urllib.request
from bs4 import BeautifulSoup

# providing url
url = "https://www.geeksforgeeks.org/how-to-automate-an-excel-sheet-in-python/?ref=feed"

# opening the url for reading
html = urllib.request.urlopen(url)

# parsing the html file
htmlParse = BeautifulSoup(html, 'html.parser')

# getting all the paragraphs
for para in htmlParse.find_all("p"):
    print(para.get_text())

Before you read this article and learn automation in Python….let’s watch a video of Christian Genco (a talented programmer and an entrepreneur) explaining the importance of coding by taking the example of automation.
You might have laughed loudly after watching this video and you surely, you might have understood the importance of automation in real life as well. Let’s come to the topic now…
We all know that Python is ruling all over the world, and we also know that Python is beginner’s friendly and it’s easy to learn in comparison to other languages. One of the best things you can do with Python is Automation. 

Consider a scenario that you’re asked to create an account on a website for 30,000 employees. How would you feel? Surely you will be frustrated doing this task manually and repeatedly. Also, this is going to take too much time which is not a smart decision. 
Now just imagine the life of employees who are into the data entry jobs. Their job is to take the data from tables such 

In [ ]:
#Methods 2: using requests and bs4
        #bs4: Beautiful Soup(bs4) is a Python library for pulling data out of HTML and XML files.
               #This module does not come built-in with Python. To install this type the below command in the terminal."pip install bs4"
        #requests: Requests allows you to send HTTP/1.1 requests extremely easily.
               #This module also does not comes built-in with Python. To install this type the below command in the terminal."pip install requests"
# import module
import requests
import pandas as pd
from bs4 import BeautifulSoup

# link for extract html data
def getdata(url):
    r = requests.get(url)
    return r.text

htmldata = getdata("https://www.geeksforgeeks.org/how-to-automate-an-excel-sheet-in-python/?ref=feed")
soup = BeautifulSoup(htmldata, 'html.parser')
data = ''
for data in soup.find_all("p"):
    print(data.get_text())

Before you read this article and learn automation in Python….let’s watch a video of Christian Genco (a talented programmer and an entrepreneur) explaining the importance of coding by taking the example of automation.
You might have laughed loudly after watching this video and you surely, you might have understood the importance of automation in real life as well. Let’s come to the topic now…
We all know that Python is ruling all over the world, and we also know that Python is beginner’s friendly and it’s easy to learn in comparison to other languages. One of the best things you can do with Python is Automation. 

Consider a scenario that you’re asked to create an account on a website for 30,000 employees. How would you feel? Surely you will be frustrated doing this task manually and repeatedly. Also, this is going to take too much time which is not a smart decision. 
Now just imagine the life of employees who are into the data entry jobs. Their job is to take the data from tables such 

In [ ]:
# imported the requests library
import requests
image_url = "https://www.python.org/static/community_logos/python-logo-master-v3-TM.png"

# URL of the image to be downloaded is defined as image_url
r = requests.get(image_url) # create HTTP response object

# send a HTTP request to the server and save
# the HTTP response in a response object called r
with open("python_logo.png",'wb') as f:

    # Saving received content as a png file in
    # binary format

    # write the contents of the response (r.content)
    # to a new file in binary mode.
    f.write(r.content)

--------------------------
**NUMPY ESSENTIALS**
-------------------------

In [2]:
#NUMPY ESSENTIALS
#1.NumPy Array:
    #1.1 Creation of NumPy Arrays from List:

import numpy as np              #First we need to "import the numpy library"
array1 = np.array([10,20,30])   #The NumPy’s array() function converts a given list into an array.
print(array1)                   #Display the contents of the array

[10 20 30]


In [7]:
#1.2 Creating a 1-D Array
array2=np.array([5,-7.4,'a',7.2])  # all integer and float values have been promoted to string, while converting the list to array.
print(array2)


['5' '-7.4' 'a' '7.2']


In [10]:
#1.3 Creating a 2-D Array
array3=np.array([[2,4,3],
            [4,7,9],[0,-1,5]])
print(array3)

[[ 2  4  3]
 [ 4  7  9]
 [ 0 -1  5]]


In [14]:
    #1.4 Attributes of NumPy Array
        #1.4.1 ndarray.ndim: gives the number of dimensions of the array as an integer value. Arrays can be 1-D, 2-D or n-D.
print(array1)
array1.ndim

[10 20 30]


1

In [19]:
        #1.4.2 ndarray.shape:It gives the sequence of integers indicating the size of the array for each dimension.
arrayx=np.array([[2,4,3],
            [4,7,9]])
print(array3)
array3.shape

[[ 2  4  3]
 [ 4  7  9]
 [ 0 -1  5]]


(3, 3)

In [22]:
        #1.4.3 ndarray.size:It gives the total number of elements of the array. This is equal to the product of the elements of shape.
print(array2)
array2.size

['5' '-7.4' 'a' '7.2']


4

In [26]:
        #1.4.4 ndarray.dtype:It is the data type of the elements of the array. All the elements of an array are of same data type. Common data types are int32, int64, float32, float64
array3.dtype

dtype('int32')

In [28]:
       #1.4.5 ndarray.itemsize:  It specifies the size in bytes of each element of the array. Data type int32 and float32 means each element of the array occupies 32 bits in memory. 8 bits form a byte. Thus, an array of elements of type int32 has itemsize 32/8=4 bytes.
print(array1)
array1.itemsize

[10 20 30]


4

2.4 Other Ways of Creating NumPy Arrays

In [31]:
#2.4 Other Ways of Creating NumPy Arrays
    #2.4.1 dtype:We can specify data type (integer, float, etc.) while creating array using "dtype" as an argument to array(). This will convert the data automatically to the mentioned type.
array4 = np.array( [ [1,2], [3,4] ] ,dtype=float)
print(array4)

[[1. 2.]
 [3. 4.]]


In [ ]:
     #2.4.2 zeros():We can create an array with all elements initialised to 0 using the function zeros(). By default, the data type of the array created by zeros() is float
array5 = np.zeros((3,4),dtype=int)
print(array5)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
     #2.4.3 ones():We can create an array with all elements initialised to 1 using the function ones(). By default, the data type of the array created by ones() is float
array6 = np.ones((3,2),dtype=int)
print(array6)


[[1 1]
 [1 1]
 [1 1]]


In [ ]:
     #2.4.4 arrange():We can create an array with numbers in a given range and sequence using the arange() function
array7 = np.arange(6)
print(array7)

# Creating an array with start value -2, end value 24 and step size 4
array8 = np.arange( -2, 24, 4 )
print(array8)

[0 1 2 3 4 5]
[-2  2  6 10 14 18 22]


2. Array indexing and Slicing

In [3]:
#2.Array indexing and Slicing
    #2.1 Array indexing
arr= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr)
print('\n')
print("Element at [2][0]=",arr[2][0]) #displays value from arr with index postion row 1 and column 0

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Element at [2][0]= 7


In [42]:
#2.Array indexing and Slicing
    #2.2 Array Slicing:  We can define which part of the array to be sliced by 
    # specifying the start and end index values  using [start : end] along with the array name

import numpy as np

# create a 1D array
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

print(array1[1:7])  # [1, 3, 5, 7, 8, 9, 2]

# slice array1 from index 0 to index 8 (exclusive) with a step size of 2
print(array1[0:8:2])  # [1 5 8 2]

# slice array1 from index 3 up to the last element
print(array1[3:])  # [7 8 9 2 4 6]

# items from start to end
print(array1[:])   # [1 3 5 7 8 9 2 4 6]

[3 5 7 8 9 2]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]


In [44]:
# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                   [9, 11, 13, 15]])

print(array1[:2, :2])

[[ 1  3]
 [ 9 11]]


3. Operations on Arrays

In [ ]:
#3.Operations on Arrays
   #3.1 Arithmetic Operations
array1 = np.array([[3,6],[4,2]])
array2 = np.array([[10,20],[15,12]])
print("-----------array1--------------")
print(array1)
print("-----------array2--------------")
print(array2)

#3.1.1 Addition
arr_add=array1 + array2
print("-----------array_addition--------------")
print(arr_add)

#3.1.2 Subtraction
arr_sub=array1 - array2
print("-----------array_subtraction--------------")
print(arr_sub)

#3.1.3 Multiplication
arr_mul=array1 * array2
print("-----------array_multiplication--------------")
print(arr_mul)

#3.1.4 Division
arr_div=array1 / array2
print("-----------array_division--------------")
print(arr_div)

#3.1.5 Exponentiation
arr_exp=array1 ** 3
print("-----------array_cube--------------")
print(arr_exp)

#3.1.6 Modulo Division
arr_mod=array2 % array1
print("-----------array_division--------------")
print(arr_mod)



-----------array1--------------
[[3 6]
 [4 2]]
-----------array2--------------
[[10 20]
 [15 12]]
-----------array_addition--------------
[[13 26]
 [19 14]]
-----------array_subtraction--------------
[[ -7 -14]
 [-11 -10]]
-----------array_multiplication--------------
[[ 30 120]
 [ 60  24]]
-----------array_division--------------
[[0.3        0.3       ]
 [0.26666667 0.16666667]]
-----------array_division--------------
[[ 27 216]
 [ 64   8]]
-----------array_division--------------
[[1 2]
 [3 0]]


In [5]:
#3.2 Transpose: Transposing an array turns its rows into columns and columns into rows
at = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]
            ])
print("----------Array before transpose-----------")
print(at)

at = at.transpose()
print("----------Array After transpose-----------")
print(at)

----------Array before transpose-----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------Array After transpose-----------
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#3.3 Sorting: Sorting is to arrange the elements of an array in hierarchical order either ascending or descending. By default, numpy does sorting in ascending order

#Sorting 1D Array
bs = np.array([1,0,2,-3,6,8,4,7])
print("----------Array before Sorting-----------")
print(bs)

print("----------Array After Sorting-----------")
bs.sort()
print(bs)

----------Array before Sorting-----------
[ 1  0  2 -3  6  8  4  7]
----------Array After Sorting-----------
[-3  0  1  2  4  6  7  8]


In [49]:
#Sorting 2D Array
   #In 2-D array, sorting can be done along either of the axes i.e., row-wise or column-wise.
   #By default, sorting is done row-wise (i.e., on axis = 1). It means to arrange elements in each row in ascending order.
   #When axis=0, sorting is done column-wise, which means each column is sorted in ascending order
arr = np.array([[10,-7,0, 20],
                [-5,1,200,40],
                [30,1,-1,4]
               ])

print("----------2D Array before Sorting-----------")
print(arr)

#default is row-wise sorting
arr.sort()
print("----------2D Array after Sorting Row-wise by default-----------")
print(arr)

#axis =0 means column-wise sorting
arr.sort(axis=0)
print("----------2D Array after Sorting columnwise-----------")
print(arr)

----------2D Array before Sorting-----------
[[ 10  -7   0  20]
 [ -5   1 200  40]
 [ 30   1  -1   4]]
----------2D Array after Sorting Row-wise by default-----------
[[ -7   0  10  20]
 [ -5   1  40 200]
 [ -1   1   4  30]]
----------2D Array after Sorting columnwise-----------
[[ -7   0   4  20]
 [ -5   1  10  30]
 [ -1   1  40 200]]


In [55]:
#3.4 Concatenating Arrays:
    #Concatenation means joining two or more arrays.
    #Concatenating 1-D arrays means appending the sequences one after another.
    #NumPy.concatenate() function can be used to concatenate two or more 2-D arrays either row-wise or column-wise.
array1 = np.array([[10, 20], [-30,40]])
array2 = np.zeros((2, 2), dtype=array1.dtype)
print('-----------Array-1------------')
print(array1)

print('-----------Array-2------------')
print(array2)

print('-----------Array-1 shape------------')
print(array1.shape)
print('-----------Array-2 shape------------')
print(array2.shape)

print('------------After concatenation array1 and array2---------------')
np.concatenate((array1,array2), axis=1)

-----------Array-1------------
[[ 10  20]
 [-30  40]]
-----------Array-2------------
[[0 0]
 [0 0]]
-----------Array-1 shape------------
(2, 2)
-----------Array-2 shape------------
(2, 2)
------------After concatenation array1 and array2---------------


array([[ 10,  20,   0,   0],
       [-30,  40,   0,   0]])

In [60]:
#3.5 Reshaping Arrays:
      #We can modify the shape of an array using the reshape() function.
      #Reshaping an array cannot be used to change the total number of elements in the array.
      #Attempting to change the number of elements in the array using reshape() results in an error.
array3 = np.arange(10,50)
print('---------------------------------')
print(array3)
print('---------------------------------')
array3.reshape(8,5)

---------------------------------
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
---------------------------------


array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
array3.reshape(2,6)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [70]:
#3.6 Splitting Arrays:
     #We can split an array into two or more subarrays.
     #numpy.split() splits an array along the specified axis.
     #We can either specify sequence of index values where an array is to be split; or we can specify an integer N, that
     #indicates the number of equal parts in which the array is to be split, as parameter(s) to the NumPy.split()function.
     #By default, NumPy.split() splits along axis=0.
import numpy as np
array=np.array([[ 10, -7, 0, 20],
                [-5, 1, 200, 40],
                [ 30, 1, -1, 4],
                [ 1, 2, 0, 4],
                [ 0, 1, 0, 2]])
print(array)


[[ 10  -7   0  20]
 [ -5   1 200  40]
 [ 30   1  -1   4]
 [  1   2   0   4]
 [  0   1   0   2]]


In [69]:
# [1,3] indicate the row indices on which to split the array
first, second, third = np.split(array, [2, 3])
print(array)
#array is split on the first row and stored on the sub-array first
print('------------First split-----------------')
print(first)

print('------------Second split-----------------')
# array is split after the first row and upto the third row and stored on the sub-array second
print(second)

print('------------Third split-----------------')
# the remaining rows of array are stored on the sub-array third
print(third)

[[ 10  -7   0  20]
 [ -5   1 200  40]
 [ 30   1  -1   4]
 [  1   2   0   4]
 [  0   1   0   2]]
------------First split-----------------
[[ 10  -7   0  20]
 [ -5   1 200  40]]
------------Second split-----------------
[[30  1 -1  4]]
------------Third split-----------------
[[1 2 0 4]
 [0 1 0 2]]


In [ ]:
#[1, 2], axis=1 give the columns indices along which to split

firstc, secondc, thirdc =np.split(array, [1, 2], axis=1)

print('------------First split-----------------')
print(firstc)

print('------------Second split-----------------')
print(secondc)

print('------------Third split-----------------')
print(thirdc)

------------First split-----------------
[[10]
 [-5]
 [30]
 [ 1]
 [ 0]]
------------Second split-----------------
[[-7]
 [ 1]
 [ 1]
 [ 2]
 [ 1]]
------------Third split-----------------
[[  0  20]
 [200  40]
 [ -1   4]
 [  0   4]
 [  0   2]]


In [ ]:
# 2nd parameter 2 implies array is to be split in 2 equal parts axis=1 along the column axis
firsthalf, secondhalf =np.split(array,2, axis=1)

print('------------First half-----------------')
print(firsthalf)

print('------------Second half-----------------')
print(secondhalf)

------------First half-----------------
[[10 -7]
 [-5  1]
 [30  1]
 [ 1  2]
 [ 0  1]]
------------Second half-----------------
[[  0  20]
 [200  40]
 [ -1   4]
 [  0   4]
 [  0   2]]


3.7 Statistical Operations on array

In [9]:
#3.7 Statistical Operations on array
import numpy as np

# create a 1D array with 5 elements
array1D = np.array([1, 2, 3, 4, 5])
print(array1D)
print('-------------------------------------')
# create a 2D array
array2D = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])
print(array2D)

[1 2 3 4 5]
-------------------------------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [12]:
#3.7.1: The max() function finds the maximum element from an array.
array1D.max()  # max element form the whole 1-D array

5

In [13]:
array2D.max()  # max element form the whole 2-D array

18

In [14]:
# if axis=1, it gives column wise maximum
array2D.max(axis=1)

array([ 6, 12, 18])

In [15]:
# if axis=0, it gives row wise maximum
array2D.max(axis=0)

array([14, 16, 18])

In [16]:
#3.7.2: The min() function finds the minimum element from an array
array1D.min() # min element form the whole 1-D array

1

In [17]:
array2D.min() # min element form the whole 2-D array

2

In [19]:
# if axis=1, it gives column wise minimum
array2D.min(axis=1)

array([ 2,  8, 14])

In [20]:
# if axis=0, it gives row wise minimum
array2D.min(axis=0)

array([2, 4, 6])

In [21]:
#3.7.3: The sum() function finds the sum of all elements of an array
array1D.sum()  # sum of all element of 1-D array

15

In [23]:
array2D.sum()  # sum of all element of 2-D array

90

In [25]:
# if axis=1, it gives sum of elements on row-wise
array2D.sum(axis=1)

array([12, 30, 48])

In [27]:
# if axis=0, it gives sum of elements on column-wise
array2D.sum(axis=0)

array([24, 30, 36])

In [28]:
#3.7.4:  The mean() function finds the average of elements of the array.
array1D.mean()

3.0

In [29]:
array2D.mean()

10.0

In [30]:
array2D.mean(axis=1)  #row-wise

array([ 4., 10., 16.])

In [31]:
array2D.mean(axis=0)  #column-wise

array([ 8., 10., 12.])

In [32]:
#3.7.5:The std() function is used to find standard deviation of an array of elements
array1D.std()

1.4142135623730951

In [33]:
array2D.std()

5.163977794943222

In [34]:
array2D.std(axis=1)  #row-wise

array([1.63299316, 1.63299316, 1.63299316])

In [35]:
array2D.std(axis=0)  #column-wise

array([4.89897949, 4.89897949, 4.89897949])